# See https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21, 24]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Build
        run: mvn -B package

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'zulu'

      - name: Build with coverage
        run: mvn -B -Pcoverage clean test jacoco:report

      - name: Publish coverage
        uses: codecov/codecov-action@v1
